# app/config/config.yml
stof_doctrine_extensions:
  orm:
    default:
      ...
      softdeleteable: true

doctrine:
  orm:
    entity_managers:
      default:
        filters:
          softdeleteable:
            class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
            enabled: true